<?php

namespace app\admin\controller;

use think\Controller;

class order extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Order();
    }

    // 显示订单页面
    public function index(){
        $field = db('order')->paginate(4);
        $this->assign('field',$field);
        return view();
    }

    // 发货
    public function deliver($id){
        $result = db('order')->find($id);
        switch ($result['status'])
        {
            case 1:
                $this->error('订单还未支付');
                break;
            case 2:
                $this->updateStatus($id);
                $this->success('发货成功');
                break;
            case 3:
                $this->error('订单已经发货');
                break;
            default:
                $this->error('订单已经发货，但库存不足');
        }
    }

    // 更改订单的支付状态
    private function updateStatus($id){
        db('order')->where('id',$id)->update(['status' => '3']);
    }
}
