<?php
/**
 * Created by PhpStorm.
 * User: mochen
 * Date: 2019-05-03
 * Time: 21:42
 */

namespace app\admin\controller;

use think\Controller;

class product extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Product();
    }

    //商品首页
    public function index(){
        $field = db('product')->select();
        $this->assign('field',$field);
        return view();
    }

    // 添加商品页面
    public function add(){
        return view();
    }

    // 点击添加商品时进行的方法
    public function store(){
        if(request()->isPost()){
            $res = $this->db->store(input('post.'));
            if($res['vaild']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg'],'add');
            }
        }
    }

    // 商品编辑
    public function edit(){
        if(request()->isPost()){
            $res = $this->db->edit(input('post.'));
            if($res['vaild']){
                $this->success($res['msg'],'index');
            }else{
                $this->error($res['msg'],'edit');
            }
        }
        // 接收category_id
        $id = input('param.id');
        // 获取旧数据
        $oldData = $this->db->find($id);
        $this->assign('oldData',$oldData);
        return view();
    }

    // 商品删除
    public function del(){
        $cateInfo = $this->db->find(input('post.id'));
        $result = $cateInfo->delete();
        if($result){
            $this->success('栏目删除成功','admin/product/index');
        }else{
            $this->error('栏目删除失败');
        }
    }


}