<?php
/**
 * Created by PhpStorm.
 * User: mochen
 * Date: 2019-05-03
 * Time: 21:42
 */

namespace app\admin\controller;

use app\admin\validate\ProductAdd as ProductAdd;
use think\Controller;
use app\admin\model\Product as ProductModel;

class product extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new ProductModel();
    }

    public function index(){
        $field = db('product')->select();
        $this->assign('field',$field);
        return view();
    }

    public function add(){
        return view();
    }

    public function store(){
        if (request()->post()) {

            $product = new ProductModel();
            $res = $product->data([
                'category_id' => input('post.category_id'),
                'name' => input('post.name'),
                'price' => input('post.price'),
                'stock' => input('post.stock'),
            ])->save();
            if ($res) {
                $this->success("添加成功", 'admin/product/index');
            } else {
                $this->error('添加失败','admin/product/add');
            }
        }
    }
}